### ISSUE TITLE
latest route

### ISSUE THREAD

**Issue by benthehorn** [shrestaz/TechNews-LSD#1]
you seem to return a json here, so it doesn't appear on the chart with the other teams athttp://138.68.91.198/chart.svg  
it should just return the number only, I think..

**Comment by expert26111** [comment]
Thank you Ben we will have a look at it tomorrow. Operation group
rocking 🤘!!!!

**Comment by expert26111** [comment]
Hi Ben we fixed it, now it returns only the hanesst_id .

**Comment by shrestaz** [comment]
To add on that, the chart was updated at 9:50 am on the 25th of November. So we're still not on the chart yet but we'll show up as soon as its updated.
